Iter13
ry461ch/metric-collector pull request #13
Opened 2024-07-16 20:05 UTC by ry461ch

2024-07-18 15:36 UTC, capsulated requested changes
В принципе, всё хорошо. Добавил несколько комментариев.

2024-07-18 15:36 UTC, capsulated commented on internal/app/agent/agent.go
> +	for i := 1; i < 7; i += 2 {
Интересный какой цикл, а почему не просто от 0 до 3? Читать очень неудобно

2024-07-18 15:36 UTC, capsulated commented on internal/app/agent/agent.go
> +	req, _ := json.Marshal(metricList)
А тут почему ошибка не логируется? Надо обязательно

2024-07-18 15:36 UTC, capsulated commented on internal/app/agent/agent.go
> +func (a *Agent) runIteration(ctx context.Context) {
Чуть чуть бы уточнить нейминг, что именно за итерация

2024-07-18 15:36 UTC, capsulated commented on internal/app/agent/agent.go
> +	cfg := config.NewConfig()
Инициализация должна быть в конструкторе. А в методе старта только то, что необходимо для старта. То есть в случае, когда, скажем, появится необходимость запускать два агента, у нас получится путанница. Думаю самое оптимальное место для этого - это конструктор приложения. А метод Run надо бы назначаить Agent'у и в нём будет for

В итоге в cmd надо будет вызвать `appAgent = agent.New(...); go appAgent.Run(...)`, либо вообще в одну строку `go agent.New(...).Run(...)`

2024-07-18 15:36 UTC, capsulated commented on internal/app/agent/config/config.go
> +type Config struct {
А почему кофиг внутри app? Все пакеты лучше создавать в корне. И только в том случае, когда прям точно необходимо сделать вложенность, либо вложенный пакет является частью текущего и нельзя его выносить - тогда можно. Иначе просто усложняется структура пакетов без необходимости и импортировать сложнее. Конфиг же глобальный и может фигурировать в любых пакетах приложения

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/config/config.go
> +package config
Также, лучше из `app` вынести. `app`  - это сборщик приложения из пакетов. `cmd` - это команда запуска приложения, там могут появится дополнительная обработка флагов или параметров для разных режимов запуска приложения

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/crontasks/snapshotmaker/snapshotmaker.go
> +	SnapshotMaker struct {
Классное имя, почти сразу понятно, что это за тип ))) 👍

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/handlers/handlers.go
> +	for i := 1; i <= 7; i += 2 {
Обязательно какую-то "обёртку" добавить для этих ретраев. Иначе полно дублирующегося кода (принцип DRY)

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/handlers/handlers.go
> +	for i := 1; i <= 7; i += 2 {
Вообще это избыточно для собсвенной БД. Ретраи полезны для обращения к  сторонним сервисам или Saas. Так как это было в задании, это ок, но в реальных проектах ретраи используются именно к сторонним API, например (но не к своим )))

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/server.go
> +func getStorage(cfg *config.Config) (storage.Storage, error) {
Это NewStorage должен быть, абстрактная фабрика. И соответсвенно, лучше убрать в пакет хранилки. А в пакете хранилки уже есть смысл создать подпакеты с разными типами хранилищ, хотя и не обязательно, но приемлемо

2024-07-18 15:36 UTC, capsulated commented on internal/app/server/server.go
> +func Run() {
Отделить бы тоже конструктор (инициализацию) от запуска. А то всё в одном методе - это немного неудобно

2024-07-18 15:36 UTC, capsulated commented on internal/models/response/response.go
> +type ResponseEmptyObject struct{}
Если это с Response относиться, тогда лучше перенести в пакет с хендлерами, так как респонсы и риквесты только на этом уровне существуют

2024-07-18 15:36 UTC, capsulated commented on internal/storage/contract.go
> +	Ping(ctx context.Context) bool
С методами Ping и Close не реализуются пустые методы в хранилке на основе памяти? Если есть пустые методы, которые добавлены только чтобы наследовать интерфейс - то надо разбить интерфейс, а на стороне вызову, один из вариантов, [проверять экземпляр на соответствие интерфейсу](https://go.dev/doc/effective_go#blank_implements)

2024-07-18 15:36 UTC, capsulated commented on internal/storage/postgres/postgres.go
> +		CREATE SCHEMA IF NOT EXISTS content;
Обычно, это init.sql в контейнере. Но у нас из-за автотестов так, к сожалению, сделать не получится. Это для справки

2024-07-18 15:36 UTC, capsulated commented on internal/storage/memory/memory.go
> +func (ms *MemStorage) GetMetric(ctx context.Context, metric *metrics.Metric) error {
Тут же где-то должны быть Ping и Close, если тип реализует интерфейс? 🤔

2024-07-18 16:08 UTC, ry461ch commented on internal/storage/postgres/postgres.go
> +		CREATE SCHEMA IF NOT EXISTS content;
Ага, пытался файлом, не получилось пройти тесты, сделал в коде

2024-07-18 16:24 UTC, ry461ch commented on internal/app/agent/config/config.go
> +type Config struct {
У меня в проекте 2 конфига - один специфичный для агента, другой специфичный для сервера. Я поместил его тут как раз из-за узкой направленности агентского пакета конфиг. Мне не кажется, что стоит делать его глобальным.

2024-07-18 16:28 UTC, ry461ch commented on internal/models/response/response.go
> +type ResponseEmptyObject struct{}
Мы в прошлый раз на 1:1 немного обсуждали, возможно недообсуждали или я что-то забыл) Мне не кажется, что response существуют только на уровне хэндлеров. Наоборот, Response - интерфейс, тут собраны возможные ответы моего сервера. И с этим интерфейсом может работать агент. Он знает, что сервер может вернуть ошибку (ErrorResponse), в которой будет текстовое поле detail, крч сможет правильно раскрасить ответ.

2024-07-18 17:56 UTC, ry461ch commented on internal/app/server/server.go
> +func getStorage(cfg *config.Config) (storage.Storage, error) {
Мне не кажется это верным. Хранилке пофик на конфигурации и это не на уровне хранили нужно выбирать подходящую реализацию. Скорее наоборот, сервер знает свой конфигурационный файл и на основе него выбирает какую хранилку использовать. Это ответственность именно сервера выбрать себе хранилку, и точно не ответственность хранили под любой конфигурационный файл возвращать нужную реализацию. В агенте, например, конфиг другой и агенту эта функция не нужна.

2024-07-18 20:34 UTC, ry461ch commented on internal/models/response/response.go
> +type ResponseEmptyObject struct{}
Вспомнил. Мы договорились, что эти структуры будут находиться в handlers, до тех пор, пока агент не завяжется на них. Как только он завяжется на ответах, перенесу в общую модель. 
Поправил

2024-07-18 20:37 UTC, ry461ch commented on internal/app/agent/config/config.go
> +type Config struct {
Перенес в отдельную папку в корне internal. Там теперь есть internal -> server -> config.go и internal -> agent -> config.go

2024-07-21 23:45 UTC, capsulated commented on internal/app/agent/config/config.go
> +type Config struct {
Да конфиг небольшой же. Можно и один пакет с двумя типами (структурами) и двумя контукторами. Хотя, кстати, можно тут вложенность создать: `config -> agent -> config.go` и `config -> server -> config.go`. Это для того, чтобы конфигурация в одном места была и масштабировать удобно было, вдруг общие объекты появятся для и того и друго конфига

2024-07-21 23:50 UTC, capsulated commented on internal/app/server/server.go
> +func getStorage(cfg *config.Config) (storage.Storage, error) {
Не обязательно конфиг, но определённые условия, при которых выбирается одна или другая реализация. Можно, скажем, вообще мок реализацию подсунуть. Сервер никак не относится к хранилке, сервер должен 'знать' только интерфейс, без каких либо деталей раализации - это очень важно момент,

2024-07-22 00:02 UTC, capsulated commented on internal/app/server/server.go
> +func getStorage(cfg *config.Config) (storage.Storage, error) {
Я скачал проект, посмотрел стируктуру папок. Тут больше абстрактный впорос, можно на 1-1 созвонится, если есть желание. Я объясню: внутренние пакеты папки app я бы перенёс в корень internal. А в app должна быть сборка приложения. А в `cmd` парсинг флагов/кофнигов (по желанию), запуск конструктора приложения и запуск самого приложения.

2024-07-22 00:05 UTC, capsulated commented on internal/models/response/response.go
> +type ResponseEmptyObject struct{}
Респосы и риквесты не бывают на уровне не HTTP. Если скажем protobuf - то это уже будет Reqaest и Reply, именно относящиеся к `grpc`. Resuest и response настолько распространены из-за повсеместно распространённого REST, что если такой нейминг будет фигурировать в других слоях, не связных именно с http запросами и ответами - то сразу собьёт с толку

2024-07-22 00:10 UTC, capsulated approved these changes
Всё отлично. Написал ответы на комментарии, думаю можно созваниваться, обсудить спорные моменты )

Апрувлю

2024-07-22 10:32 UTC, merged