Iter5
ry461ch/metric-collector pull request #5
Opened 2024-06-13 16:37 UTC by ry461ch

2024-06-15 14:06 UTC, capsulated requested changes
Отлично организованы типы с методами (структуры). Но есть небольшие замечания по организации пакетов (папок) и по неймингу, и по `cmd`. См коменты

2024-06-15 14:06 UTC, capsulated commented on cmd/agent/main.go
> +type Config struct {
Все объекты описаны в пакете `cmd`, их необходимо переместить в пакеты (или на крайний случай в корень приложения). `cmd` это папка инициализации и старта приложения, реализаций тут быть не должно

2024-06-15 14:06 UTC, capsulated commented on cmd/agent/main.go
> +func (agent *MetricAgent) CollectMetric() {
Для MetricAgent можно пакет в корне создать, папку `agent` на уровне `cmd`, либо internal

2024-06-15 14:06 UTC, capsulated commented on cmd/agent/main.go
> +func main() {
То есть,  в `cmd` только  этот main() должен остаться. Может какие-то глобальные переменные конфигурации (если их немного)

2024-06-15 14:06 UTC, capsulated commented on cmd/server/metric_server.go
> +type MetricUpdateServer struct {
Я бы переименовал в `Handlers`, `HandlerService` или `MetricHandlers`

2024-06-15 14:06 UTC, capsulated commented on cmd/server/metric_server.go
> +func (server *MetricUpdateServer) postGaugeHandler(res http.ResponseWriter, req *http.Request) {
Ресивер принято называть по первому символу имени типа, либо нескольких заглавным. Если использовать без сокращений, с пределах метода проще "потерять". Это аналог this/self других ЯП

2024-06-15 14:06 UTC, capsulated commented on cmd/server/metric_server.go
> +type MetricUpdateServer struct {
Ниже увидел и конфигурацию роутера в этом типе. Вообще, можно ещё один объект можно создать для роутера и передать ссылку в конструктор сервера. Но если это сервер, то и сам ListenAndServe хорошо бы реализовать. 

На мой взгляд можно сделать либо два, либо три объекта: `Router`, `Handlers`, `Server` либо `Router` (месте с хендлерами) и `Server`

2024-06-15 14:06 UTC, capsulated commented on cmd/server/middlewares.go
> +func middlewareValidateContentType(next http.Handler) http.Handler {
Для миддлевари лучше создать отдельный пакет в корне. См пример в репозитории chi.Router, как там реализованы мидлвари. Кстати, миддлвари будем проходить только в след спринтах

2024-06-15 14:06 UTC, capsulated commented on cmd/server/metric_server.go
> +func (server *MetricUpdateServer) MakeRouter() chi.Router {
Это конструктор, должен быть с именем New, например `NewRouter()` рекомендация по именам конструктора [тут](https://go.dev/doc/effective_go#composite_literals)

2024-06-15 14:06 UTC, capsulated commented on internal/storage/storage.go
> +func (storage *MetricStorage) UpdateGaugeValue(key string, value float64) {
То же, ресивер сокращенный должен быть:
```go
// StorageR
type Storager interface { ... }

type Storage struct {
	counter map[string]int64 
	gauge   map[string]float64
}

func (s *Storage) UpdateGaugeValue(key string, value float64) { ... }
...
```

2024-06-15 14:06 UTC, capsulated commented on internal/storage/storage.go
> +type Storage interface {
Интерфейсы описываются в местах использования, а не в местах реализации

2024-06-18 22:19 UTC, capsulated approved these changes
Всё супер! Критичных замечаний нет

Апрувлю, но оставил коменты, их необходимо учесть в следующем спринте

2024-06-18 22:19 UTC, capsulated commented on cmd/agent/main.go
> +	parsers.ParseArgs(&options)
Так парсер вроде к конфигу относится. Может его в пакет конфиг переместить?

2024-06-18 22:19 UTC, capsulated commented on internal/agent/runner/agent.go
Целый пакет `runner` внутри пакета`agent` кажется многовато. Я предлагаю в корень папки (пакета) `agent`  переместить. Сам пакет получился супер 👍

2024-06-18 22:19 UTC, capsulated commented on internal/agent/runner/agent.go
> +func NewAgent(timeState *config.TimeState, options config.Options, mStorage storage) Agent {
И здесь `Agent` можно удалить, оставив просто `New` так как совпадает с именем пакета (это из рекомендаций комьюнити go)

2024-06-18 22:19 UTC, capsulated commented on internal/models/netaddr/netaddr.go
> +type NetAddress struct {
Ох какой сложный объект получился для простого адреса. Я бы его упростил до простой конкантенации строки. Смотри сам, можно и оставить, но в конфиг его бы переместить

2024-06-18 22:19 UTC, capsulated commented on internal/server/handlers/handlers.go
> +type Handlers struct {
Супер, удобно и читаемо 👍

2024-06-18 22:19 UTC, capsulated commented on internal/server/router/contract.go
> +type service interface {
Имя очень общее. Чуть чуть уточнить бы: `handlers` или `metricHandler` или `apiHandler`? Ну или что-то похожее

2024-06-18 22:19 UTC, capsulated commented on internal/server/router/router.go
> +func NewRouter(service service) chi.Router {
Здесь также, можно оставить только `New` так как совпадает с именем пакета

2024-06-18 22:19 UTC, capsulated commented on internal/storage/memory/memory.go
> +func NewMemStorage() MemStorage {
А если в конструктор пустой, то можно просто на &MemStorage{} заменить в местах вызова.

Кстати, вопрос на засыпку: почему возвращаемое значение передаётся по значению, а не указателю вот так:
```go
func NewMemStorage() *MemStorage {
```

Это важный момент для понимания

2024-06-19 06:12 UTC, ry461ch commented on internal/storage/memory/memory.go
> +func NewMemStorage() MemStorage {
Полагаю, потому что объект сотрется после выхода из функции (или после garbage-collector-a?) и указатель будет nil?

2024-06-19 06:20 UTC, ry461ch commented on internal/models/netaddr/netaddr.go
> +type NetAddress struct {
Объект используется и в агенте и на сервере. Ты имеешь в виду сделать общую папочку конфиг и туда переместить папочку netaddr?

2024-06-19 06:25 UTC, merged

2024-06-19 07:06 UTC, ry461ch commented on internal/storage/memory/memory.go
> +func NewMemStorage() MemStorage {
типа время жизни созданного внутри функции ограничено этой самой функцией

2024-06-30 17:14 UTC, capsulated commented on internal/models/netaddr/netaddr.go
> +type NetAddress struct {
А он нужен вообще? Может просто в конструкторе собирать строку?