Iter9
ry461ch/metric-collector pull request #9
Opened 2024-06-27 16:01 UTC by ry461ch

2024-06-30 18:02 UTC, capsulated requested changes
Комментарии написал. Если не согласен с чем-то: ответ на комент приветствуется, только обязательно с аргументацией выбранного решения.

Также, надо подумать (хоть как-то), про `штатное завершение сервиса` из задания

2024-06-30 18:02 UTC, capsulated commented on internal/agent/agent.go
> +func New(timeState *TimeState, options config.Options, mStorage storage) Agent {
В большинсnве - возвращаем указатель на экземпляр. Конструктор в го - это  паттерн 'фабричный метод'. Бывают случаи когда возвращаетсмя интерфейс. Но выходное значение возвращать по значению (а не указателю) - это должен быть особый исключительный случай

2024-06-30 18:02 UTC, capsulated commented on internal/agent/agent.go
>  	return Agent{timeState: timeState, options: options, mStorage: mStorage}
```go
func New(timeState *TimeState, options config.Options, mStorage storage) *Agent {
	return &Agent{timeState: timeState, options: options, mStorage: mStorage}
}
```

Хотя в конструкторе нет никакой логики, можно и не создавать метод `New()`, а непосредственно такую конcтрукцию использовать в месте вызова метода: 
```go
agent := &Agent{
   timeState: timeState,
   options: options,
   storage: storage
}
```

2024-06-30 18:02 UTC, capsulated commented on internal/agent/config/config.go
> +	Options struct {
А зачем отдельный тип `Options`? Может всё в одном конфиге сделать?

2024-06-30 18:02 UTC, capsulated commented on internal/helpers/metricfilehelper/contract.go
> +type storage interface {
Интерфейс описывается в месте использования. А в данном случае, почему-то, в хелперах?

2024-06-30 18:02 UTC, capsulated commented on internal/helpers/metricfilehelper/metricfilehelper.go
> +func SaveToStorage(filePath string, mStorage storage) error {
Может всё же дополнительный пакет с методами Import/Export To Disk? И его внедрить, как зависимость, в хранилке? Просто методы  на уровне пакета - это не очень гибкие конструкции. Лучше создать воркер: описать тип с конcтруктором и параметрами, который реализует методы дампа на диск

2024-06-30 18:02 UTC, capsulated commented on internal/helpers/metricfilehelper/contract.go
> +type storage interface {
И не экспортируемый... Это странно, должен использоваться же в пакетах хендлеров или сервисном слое

2024-06-30 18:02 UTC, capsulated commented on internal/helpers/metricmodelshelper/contract.go
> +type storage interface {
Это ещё один интерфейс? Дублирование кода - ошибка, нарушение принципа DRY. Нужен один интерфейс для хранилки, а реализаций, на основе этого интерфейса, может быть много: `MemStorage`, `PostgresStorage`, `FileStorage` и все наследовать будут единственный интерфейс `Storage`

2024-06-30 18:02 UTC, capsulated commented on internal/helpers/metricmodelshelper/metricmodelshelper.go
> +func SaveMetrics(metricList []metrics.Metrics, mStorage storage) error {
Это похоже на сервисный слой архитектуры. Можно создать тип+конcтруктор, по классике (к примеру, `MetricService`), с методами:
```go
// Тут описывать интерфейс storage
type Storage interface {
    SaveMetric(...) ...
    ReadMetric(...) ...
}


type MetricService strcut {
   storage: Storage
}

func NewMetricService(storage: Storage) {
   return &MetricService{
      storage: storage,
   }
}

func (m *MetricService) ExtractMetrics(mStorage storage) ([]metrics.Metrics, error) {
   metrics, err := m.storage.GetMetric(...)
   if err != nil { ... }
   
   return metrics, nil
}
```

В таком виде зависимость на storage мы передаём один раз в конструктор, не передавая в каждом методе

2024-06-30 18:02 UTC, capsulated commented on internal/models/response/response.go
> +package response
Это точно должно быть не в моделях, а в пакете, скорее всего, хендлеров. Так как больше ничего использоваться эти сущности не будут и связаны с response - значит точно server или handlers

2024-06-30 18:02 UTC, capsulated commented on internal/server/crontasks/snapshotmaker/contract.go
> +type storage interface {
Третий интерфейс для storage? Это явно что-то не то. Если используется особый подход (текущая реализация контрактов с виду похожа на usecases), типа DDD или CleanArchitecture или что-то ещё - то необходимо обязательно добавить описание подхода в README.md. Чем является `contract`, что такое `model` (и другие абстрактные сущности из каких-то подходов, типа usecase, domain, controller)  -  обязательно описать в README.md

2024-06-30 18:02 UTC, capsulated commented on internal/server/crontasks/snapshotmaker/snapshotmaker.go
> +package snapshotmaker
Ну и не в пакете server это должно быть, а отдельно, в корне скорее всего

2024-06-30 18:02 UTC, capsulated commented on internal/server/handlers/handlers.go
> +func New(mStorage storage, options config.Options) Handlers {
А почему `mStorage`? Может просто `storage`? Вдруг реализация измениться на fileStrorage или dbStorage, тогда всё переименовывать придётся?

2024-06-30 18:02 UTC, capsulated commented on internal/server/logger/logger.go
> +package slogger
Имя пакета отличается от имени папки - сбивает с толку. И перенести надо из пакета сервера в пакет `internal`, а лучше вообще в `pkg/logger` в корне, чтобы потом использовать можно было в выпускной работе или pet проекте, к примеру, не создавая по-новой

2024-06-30 18:02 UTC, capsulated commented on internal/server/middlewares/content_type.go
> +package middlewares
`middleware` также, лучше вынести в `internal` или в корень или в `pkg` (pkg, на мой взгляд, идеально)

2024-06-30 18:02 UTC, capsulated commented on internal/server/middlewares/gzip.go
> +type gzipWriter struct {
Gzip тоже отдличный претендент на независимый пакет к примеру `Compressor` и в pkg: `pkg/compressor`

2024-06-30 18:02 UTC, capsulated commented on internal/server/router/contract.go
> +type metricHandlers interface {
Имя хорошее. Но в рамках спринтов нам этот интерфейс не понадобится. Если только используется в рамках тестов/моков - тогда ок

2024-06-30 18:02 UTC, capsulated commented on internal/server/server.go
> +func Run() {
Вот я бы сервер и агент положил в `internal/app/server` и `internal/app/agent`. И добавить по-хорошему конструкторы:
```go
type MetricServer struct { ... }

func NewMetricServer() (*MetricServer, error) { ... }

func (a *MetricServer) Run() { ... }
func (a *MetricServer) Stop() { ... }
```
Нейминг примерный

2024-07-03 10:47 UTC, ry461ch commented on internal/agent/config/config.go
> +	Options struct {
тяжеловато пользоваться библиотекой github.com/caarlos0/env/v6. env.Parse(&cfg) парсит входные переменные окружения, но непонятно как отличать ситуации, когда приходит ENV_VARIABLE=0 и когда ENV_VARIABLE не приходит совсем (в обоих случаях значение в Config будет = 0). После долгих размышлений пришел к решению сделать структуру Config только со строковыми значениями, а потом перегонять в Options. Если в config значение переменной равно пустой строке, то можно считать, что переменная окружения не задана и значение в options останется прежним, которое было до Парсинга config.

2024-07-03 10:53 UTC, ry461ch commented on internal/helpers/metricfilehelper/contract.go
> +type storage interface {
"Интерфейс описывается в месте использования" - интерфейс и используется в хелперах, поэтому там и объявлен контракт...

2024-07-03 12:56 UTC, ry461ch commented on internal/server/crontasks/snapshotmaker/snapshotmaker.go
> +package snapshotmaker
Тут не оч согласен. У нас есть сервис, в нем и только в нем могут запускаться дополнительные кронтаски специфичные только для этого сервиса.

2024-07-03 12:59 UTC, ry461ch commented on internal/server/router/contract.go
> +type metricHandlers interface {
Вообще да, попытался разделить классы хэндлеров и роутера, чтобы на уровне тестов можно было независимо покрыть юниттестами оба класса

2024-07-03 13:12 UTC, ry461ch commented on internal/server/handlers/handlers.go
> +func New(mStorage storage, options config.Options) Handlers {
имеется в виду metricStorage. Просто storage не хочется использовать, ибо так называется пакет с интерфейсом Storage. Ща подумаю как быть

2024-07-03 13:17 UTC, ry461ch commented on internal/server/crontasks/snapshotmaker/contract.go
> +type storage interface {
Я пока плохо понимаю, где и как принято объявлять интерфейсы. 
В моем коде во всех маломальски независимых пакетах я пытался объявить интерфейс storage. Потому что именно так понимал фразу "Интерфейс описывается в месте использования". Раз в пакетах используется интерфейс Storage - то там его и нужно объявить. Отсюда 10 интерфейсов Storage)) 

Файлик contract.go сделал из-за советов наставника на первом семинаре, где он показывал как отделяет внешние интерфейсы, которые используются в пакете, от логики пакета.

2024-07-03 13:21 UTC, ry461ch commented on internal/models/response/response.go
> +package response
Это взял из других ЯП. Типа базовая архитектура сервиса - папочка api с перечислением ручек и первичной логикой обработки запросов, потом папочка models с описанием всех моделей, используемых в сервисе, ну и тд.

2024-07-03 13:26 UTC, ry461ch commented on internal/models/response/response.go
> +package response
Но все же коммент про то, что эти сущности нигде кроме хендлеров не будут использоваться - не верен. Я вполне могу обрабатывать эти модели в агенте, просто этого не делаю. 

Я бы даже сказал, верно что эти модели вне папки server, потому что это, можно сказать, недоделанная часть openapi моего сервера. Клиенты должны знать какие модели могут прийти в ответах моего сервера

2024-07-03 13:29 UTC, ry461ch commented on internal/server/crontasks/snapshotmaker/contract.go
> +type storage interface {
Сделал один contract.go в папке storage. Но пока не понимаю тогда фразу "Интерфейс описывается в месте использования".

2024-07-03 14:14 UTC, ry461ch commented on internal/server/handlers/handlers.go
> +func New(mStorage storage, options config.Options) Handlers {
сделал везде metricStorage

2024-07-03 14:23 UTC, ry461ch commented on internal/helpers/metricmodelshelper/metricmodelshelper.go
> +func SaveMetrics(metricList []metrics.Metrics, mStorage storage) error {
действительно это сервизный слой архитектуры, но только для сервера. Проблема в том, что в агенте мы тоже используем metricmodelshelper, поэтому в виде функций-хелперов изначально сделал

2024-07-03 16:20 UTC, ry461ch commented on internal/agent/agent.go
>  	return Agent{timeState: timeState, options: options, mStorage: mStorage}
Мне не очень нравится такой подход, я бы оставил New. Просто из соображения, что хочется внутренние options, timeState и тд закрыть для доступа извне. С функцией New можно будет создать экземпляр агента и быть уверенным, что в середине работы агента его поля не поменяются.

2024-07-03 17:21 UTC, ry461ch commented on internal/agent/agent.go
>  	return Agent{timeState: timeState, options: options, mStorage: mStorage}
Указатель будет возвращать - да

2024-07-03 21:22 UTC, ry461ch commented on internal/helpers/metricfilehelper/contract.go
> +type storage interface {
Перенес интерфейс стораджа в одно место, раз нельзя в каждой папке использования дублировать. Не оч тогда понимаю "Интерфейс описывается в месте использования"

2024-07-03 21:24 UTC, ry461ch commented on internal/helpers/metricmodelshelper/contract.go
> +type storage interface {
Хелп, я не понимаю. Так где интерфейс определять - в месте использования (хелпер, агент, сервер) или в одном месте, откуда потом реализации пойдут memStorage, FileStorage и тд?

2024-07-03 21:33 UTC, ry461ch commented on internal/server/server.go
> +func Run() {
Не понимаю зачем сервер и клиент в одну папку класть. Это же разные совершенно сущности, а не части одного приложения..
Можно не буду этого делать или объясни зачем это нужно

2024-07-03 21:37 UTC, ry461ch commented on internal/server/crontasks/snapshotmaker/contract.go
> +type storage interface {
Объясни плиз, что ты имеешь в виду под местом использования:
1) Если места, где этот интерфейс используется, то их много, отсюда и дубликаты интерфейсов
2) Если место, откуда потом наследуется memStorage, то ок, сделал пока так

2024-07-05 02:40 UTC, capsulated commented on internal/agent/agent.go
>  	return Agent{timeState: timeState, options: options, mStorage: mStorage}
👌

2024-07-05 02:50 UTC, capsulated commented on internal/agent/config/config.go
> +	Options struct {
В `README.md` раздел об этом: https://github.com/caarlos0/env/blob/main/README.md#init-nil-pointers

2024-07-05 02:51 UTC, capsulated commented on internal/helpers/metricfilehelper/contract.go
> +type storage interface {
https://go.dev/wiki/CodeReviewComments#interfaces

2024-07-05 02:56 UTC, capsulated commented on internal/server/middlewares/content_type.go
> +package middlewares
Для примера, можно посмотреть на chi  https://github.com/go-chi/chi/tree/master/middleware

2024-07-05 02:57 UTC, capsulated commented on internal/server/server.go
> +func Run() {
Это как пример, иногда пишут и так. Делать необязательно

2024-07-05 03:12 UTC, capsulated approved these changes
Я апрувлю, но есть много замечаний по организации объектов

Если коротко, то замечания следующие:
- целых три пакета `config`
- модель `response` не должна быть глобальной
- `agent` и `server` надо бы положить в `app`
- пакеты в `internal` не нужно делить на `agent` и `server`, так как сущности надо создавать таким образом, чтобы была возможность использовать не только для конкретных сервера и агента
- вызовы конструкторов внутри конструкторов лучше убрать
- лишние интерфейсы лучше минимизировать 

Запишись, пожалуйста, на 1-1, так как очень много придётся в комментариях аргументировать все эти пункты, а голосом и с шарингом экрана можно обсудить все эти вопросы намного продуктивнее

2024-07-05 03:12 UTC, capsulated commented on internal/models/response/response.go
> +package response
'Универсальность' - это только минус. 'Малая связность' - вот что плюс. Если ты используешь сущность `response` и всё, что связаны с http завпросами где-то за рамками хендлеров - ты нарушаешь Single Responsabiliy прицнип из solid

2024-07-10 14:59 UTC, merged